### PR TITLE
Basic database up and running

### LINKED ISSUE #27: Basic database up and running
### Assumptions 
Ready tables to be set up later

### PR DESCRIPTION
**Pull request by carlosreiakvam-uit**
closes #27 

Hint: Syntaksen over close'er issue nr 27, basic_database_up_and_running når merge er gjort.
**Denne branchen skal kun sørge for at databasen er oppe å kjøre**  
**Forbedring av database-design flyttes til ny issue** #44   

~~**Test gjerne med noen verdier og se om databasen fungerer som forventet før dere trykker approved** 🦄~~

### CODE REVIEW

**Comment by sanehint** [comment]
Får en feilmelding 

Traceback (most recent call last):
  File "/Users/hansteinrommerud/sync/datateknikk/systemutvikling DTE-2604/Matplanlegger---Systemutvikling-Ne-3--Munchies-/backend/server.py", line 17, in <module>
    app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 1017, in run_simple
    inner()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 957, in inner
    srv = make_server(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 789, in make_server
    return ThreadedWSGIServer(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 693, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use

**Comment by sanehint** [comment]
Får en feilmelding 

Traceback (most recent call last):
  File "/Users/hansteinrommerud/sync/datateknikk/systemutvikling DTE-2604/Matplanlegger---Systemutvikling-Ne-3--Munchies-/backend/server.py", line 17, in <module>
    app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 1017, in run_simple
    inner()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 957, in inner
    srv = make_server(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 789, in make_server
    return ThreadedWSGIServer(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 693, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use

**Comment by Stianlyng** [comment]
Ser ut som du har python 3.9 @sanehint

**Comment by sanehint** [comment]
Var Python 3.9 feil?

**Comment by Stianlyng** [comment]
Oppdater til  siste. 3.10 something

**Comment by sanehint** [comment]
Prøver det

**Comment by sanehint** [comment]
Ser ikke ut som det var problemet, btw - jeg restartet containeren i docker, så den kjører nå. Kjører stadig 3.9

**Review by Stianlyng — APPROVED** [review]
Alt fungerer "as intended". Videre arbeid med tabellene gjennstår

**Comment by jebisseth-uit** [comment]
Noen feil:
- Kobling nødvendig mellom usergroup og weeklymenu
- Tabell for type bruker (restaurant, familie) koblet mot user
- Description i recipe kan ikke være longblob (forventer fil)
- Weeklymenu trenger id (sammesatt år og uke gir kun mulighet for én oppskrift per uke)

**Review by jebisseth-uit — APPROVED** [review]

**Comment by carlosreiakvam-uit** [comment]
> Noen feil:
> 
> * Kobling nødvendig mellom usergroup og weeklymenu
> * Tabell for type bruker (restaurant, familie) koblet mot user
> * Description i recipe kan ikke være longblob (forventer fil)
> * Weeklymenu trenger id (sammesatt år og uke gir kun mulighet for én oppskrift per uke)

Hvis noen ikke fikk det med seg: Disse feilene rettes nå i issue #44

**Pull request merged**
